CREATE TYPE citrus_family AS ENUM ('orange', 'pamplemousse', 'citron', 'clémentine', 'mandarine', 'kumquat');

CREATE TABLE species (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scientific_name text NOT NULL UNIQUE,
  common_name text NOT NULL UNIQUE,
  family citrus_family NOT NULL
);

INSERT INTO species (scientific_name, common_name, family) VALUES
('Citrus sinensis L.', 'orange douce', 'orange'),
('Citrus aurantium L.', 'orange amère', 'orange'),
('Citrus maxima', 'pamplemousse', 'pamplemousse'),
('Citrus x paradisi', 'pomelo', 'pamplemousse'),
('Citrus x tangelo', 'tangelo', 'pamplemousse'),
('Citrus x limon', 'citron jaune', 'citron'),
('Citrus medica L.', 'cédrat', 'citron'),
('Citrus hystrix', 'combava', 'citron'),
('Citrus aurantiifolia', 'citron vert', 'citron'),
('Citrus bergamia', 'bergamote', 'citron'),
('Citrus x clementina', 'clémentine', 'clémentine'),
('Citrus reticulata', 'mandarine', 'mandarine'),
('Citrus x tangerina', 'tangerine', 'mandarine'),
('Citrus japonica', 'kumquat', 'kumquat'),
('Citrus x floridana', 'limequat', 'kumquat');

CREATE TABLE variety (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cultivar text NOT NULL,
  bitterness int NOT NULL CHECK (bitterness <= 5 AND bitterness >= 0),
  juiciness int NOT NULL CHECK (juiciness <= 5 AND juiciness >= 0),
  species_id int NOT NULL REFERENCES species (id),
  UNIQUE (cultivar, species_id)
);

INSERT INTO variety (cultivar, bitterness, juiciness, species_id) VALUES
('Osbeck', 4, 5, 1),
('Moro', 5, 5, 1),
('Sanguinello', 2, 5, 1),
('Hook', 3, 0, 2),
('Honey', 5, 3, 3),
('Sweetie', 2, 5, 3),
('Chandler', 2, 1, 3),
('Oro blanco', 0, 1, 4),
('Rio star', 2, 2, 4),
('Seminole', 2, 1, 5),
('Bonnie Brae', 0, 0, 6),
('Eureka', 3, 5, 6),
('Etrog', 2, 2, 7),
('Sarcodactylis', 3, 4, 7),
('Westeri', 4, 0, 8),
('sur Macrophylla', 0, 3, 9),
('Bergamia', 0, 0, 10),
('Algérienne', 3, 2, 11),
('Clémenvilla', 5, 1, 11),
('Clémenule', 3, 4, 11),
('Deliciosa', 4, 5, 12),
('Tachibana', 3, 1, 12),
('Ponkan', 0, 4, 12),
('Tanger', 3, 3, 13),
('Moragne', 0, 5, 13),
('Dancy', 5, 1, 13),
('Marumi', 5, 3, 14),
('Meiwa', 0, 1, 14),
('Swinglei', 5, 4, 14),
('Eustis', 0, 4, 15),
('Margarita', 5, 0, 15);